### ISSUE TITLE
Add other crypto currencies

### ISSUE THREAD

**Issue by spaceVStab** [spaceVStab/bitcoin-cli#2]
Similar to bitcoin price index, the cli should have options for other crypto currencies too like litecoin and else.

**Comment by drowolath** [comment]
Hi @spaceVStab, I will try to add an option that will take in other crypto currencies and get their exchange rate

**Comment by smritigambhir** [comment]
@drowolath  are you working on this then? Let me know if you aren't.

**Comment by spaceVStab** [comment]
@drowolath Yeah definitely. But how are u planning to do that?

**Comment by drowolath** [comment]
@smweetee I am indeed

@spaceVStab I recently came accross this API (https://coinmarketcap.com/api/) that, among other things, provides the exchange rate for several crypto currencies. I was planning on adding an option to click.command and provide the requested infos.

**Comment by spaceVStab** [comment]
@drowolath That's a nice idea. You can add functionality if user opts for other currencies. Cool.
